namespace AxsCsvViewer.Models
{
    public class Sale
    {
        public string unique_id { get; set; }
        public string transaction_id { get; set; }
        public string context_id { get; set; }
        public string context_name { get; set; }
        public string action_date { get; set; }
        public string customer_id { get; set; }
        public string order_id { get; set; }
        public string channel { get; set; }
        public string outlet { get; set; }
        public string Operator { get; set; }
        public string offer_lookup { get; set; }
        public string offer_name { get; set; }
        public string offer_type { get; set; }
        public string venue_id { get; set; }
        public string venue { get; set; }
        public string venue_address { get; set; }
        public string venue_city { get; set; }
        public string venue_state { get; set; }
        public string venue_zip { get; set; }
        public string product_id { get; set; }
        public string primary_product_id { get; set; }
        public string product { get; set; }
        public string merchandise_product_name { get; set; }
        public string product_type { get; set; }
        public string inventory_type { get; set; }
        public string entity_id { get; set; }
        public string entity { get; set; }
        public string client_id { get; set; }
        public string client { get; set; }
        public string event_id { get; set; }
        public string event_lookup { get; set; }
        public string event_name { get; set; }
        public string event_start_date { get; set; }
        public string event_end_date { get; set; }
        public string event_build_date { get; set; }
        public string zone_type { get; set; }
        public string zone_name { get; set; }
        public string event_zone_gl_code { get; set; }
        public string fee_id { get; set; }
        public string fee_name { get; set; }
        public string fee_type { get; set; }
        public string fee_component_type { get; set; }
        public string fee_component_id { get; set; }
        public string fee_component { get; set; }
        public string fee_component_revenue_center_name { get; set; }
        public string fee_component_revenue_center_code { get; set; }
        public string fee_component_revenue_center_remittance_account { get; set; }
        public string fee_gross_amount { get; set; }
        public string fee_net_amount { get; set; }
        public string fee_tax_amount { get; set; }
        public string price_code_type { get; set; }
        public string price_code { get; set; }
        public string price_mode { get; set; }
        public string method_of_delivery_type { get; set; }
        public string method_of_delivery { get; set; }
        public string reference_price { get; set; }
        public string merch_price_component_id { get; set; }
        public string current_paid_amount { get; set; }
        public string variant_sku { get; set; }
        public string merch_gross_amount { get; set; }
        public string merch_net_amount { get; set; }
        public string merch_tax_amount { get; set; }
        public string ticket_component_base_gross_amount { get; set; }
        public string ticket_component_base_net_amount { get; set; }
        public string ticket_component_base_tax_amount { get; set; }
        public string ticket_component_base_revenue_center_name { get; set; }
        public string ticket_component_base_revenue_center_code { get; set; }
        public string ticket_component_base_revenue_center_remittance_account { get; set; }
        public string ticket_component_uplift_gross_amount { get; set; }
        public string ticket_component_uplift_net_amount { get; set; }
        public string ticket_component_uplift_tax_amount { get; set; }
        public string ticket_component_uplift_revenue_center_name { get; set; }
        public string ticket_component_uplift_revenue_center_code { get; set; }
        public string ticket_component_uplift_revenue_center_remittance_account { get; set; }
        public string ticket_component_1_gross_amount { get; set; }
        public string ticket_component_1_net_amount { get; set; }
        public string ticket_component_1_tax_amount { get; set; }
        public string ticket_component_1_revenue_center_name { get; set; }
        public string ticket_component_1_revenue_center_code { get; set; }
        public string ticket_component_1_revenue_center_remittance_account { get; set; }
        public string ticket_component_2_gross_amount { get; set; }
        public string ticket_component_2_net_amount { get; set; }
        public string ticket_component_2_tax_amount { get; set; }
        public string ticket_component_2_revenue_center_name { get; set; }
        public string ticket_component_2_revenue_center_code { get; set; }
        public string ticket_component_2_revenue_center_remittance_account { get; set; }
        public string ticket_component_3_gross_amount { get; set; }
        public string ticket_component_3_net_amount { get; set; }
        public string ticket_component_3_tax_amount { get; set; }
        public string ticket_component_3_revenue_center_name { get; set; }
        public string ticket_component_3_revenue_center_code { get; set; }
        public string ticket_component_3_revenue_center_remittance_account { get; set; }
        public string ticket_component_4_gross_amount { get; set; }
        public string ticket_component_4_net_amount { get; set; }
        public string ticket_component_4_tax_amount { get; set; }
        public string ticket_component_4_revenue_center_name { get; set; }
        public string ticket_component_4_revenue_center_code { get; set; }
        public string ticket_component_4_revenue_center_remittance_account { get; set; }
        public string ticket_component_5_gross_amount { get; set; }
        public string ticket_component_5_net_amount { get; set; }
        public string ticket_component_5_tax_amount { get; set; }
        public string ticket_component_5_revenue_center_name { get; set; }
        public string ticket_component_5_revenue_center_code { get; set; }
        public string ticket_component_5_revenue_center_remittance_account { get; set; }
        public string total_sales_gross_amount { get; set; }
        public string total_sales_net_amount { get; set; }
        public string total_sales_tax_amount { get; set; }
        public string quantity { get; set; }
        public string order_item_id { get; set; }
        public string ticket_component_base_uid { get; set; }
        public string ticket_component_uplift_uid { get; set; }
        public string ticket_component_1_uid { get; set; }
        public string ticket_component_2_uid { get; set; }
        public string ticket_component_3_uid { get; set; }
        public string ticket_component_4_uid { get; set; }
        public string ticket_component_5_uid { get; set; }
        public string ticket_component_base_price_component_id { get; set; }
        public string ticket_component_uplift_price_component_id { get; set; }
        public string ticket_component_1_price_component_id { get; set; }
        public string ticket_component_2_price_component_id { get; set; }
        public string ticket_component_3_price_component_id { get; set; }
        public string ticket_component_4_price_component_id { get; set; }
        public string ticket_component_5_price_component_id { get; set; }
        public string fee_component_uid { get; set; }
        public string fee_price_component_id { get; set; }
        public string merch_component_uid { get; set; }
        public string merch_price_component_id2 { get; set; }
        public string related_ticket_order_item_id { get; set; }
        public string merch_component_revenue_center_name { get; set; }
        public string merch_component_revenue_center_code { get; set; }
        public string ticket_component_base_name { get; set; }
        public string ticket_component_uplift_name { get; set; }
        public string ticket_component_1_name { get; set; }
        public string ticket_component_2_name { get; set; }
        public string ticket_component_3_name { get; set; }
        public string ticket_component_4_name { get; set; }
        public string ticket_component_5_name { get; set; }
        public string merch_component_name { get; set; }
    }
}
